### ISSUE TITLE
Contrast errors in people page

### ISSUE THREAD

**Issue by bebatut** [open-life-science/open-life-science.github.io#438]
I ran [Wave](https://wave.webaim.org/) to check for accessibility on the website.
In the people pages, I got many errors because of contrast in the people information:

![image](https://user-images.githubusercontent.com/1842467/194894288-559d064a-4223-48a3-8d0d-035f441ad4da.png)

It would be good to fix them

**Comment by baimamboukar** [comment]
I want to work on this!
I am kinda confused.... What do you mean by contrast here ?
Thanks for clarifying @bebatut

**Comment by baimamboukar** [comment]
Thanks for the clarifications! 
I will soon raise a pull request about this....☄️

**Comment by Njong392** [comment]
> It seems that some components in the page have really low contrast, which make them hard to be seen. You can install the wave extension in your browser and activate it on the people page to see where these components are in order to fix them

Okay, I found a nice color that could get the contrast issue to sit better. @bebatut is there a specific CSS file that needs updating for the contrast issue to be resolved?
![Screenshot from 2022-10-11 22-37-55](https://user-images.githubusercontent.com/81039882/195203406-f73dbed4-9897-436a-8d06-13de0e58ff81.png)

**Comment by lisaomoh101** [comment]
@baimamboukar can i work with you on this if still avaliable, please DM me on the slack page @Lisa omojevwe

**Comment by baimamboukar** [comment]
> @baimamboukar can i work with you on this if still avaliable, please DM me on the slack page @Lisa omojevwe
> 

Hello @lisaomoh101...

Yes it is still available ☄️

**Comment by lisa** [comment]
> @baimamboukar can i work with you on this if still avaliable, please DM me on the slack page @lisa omojevwe

# `@lisa` User Notification

Hello! You're receiving this notice because you've tagged me, @lisa, on GitHub, likely in error. Lisa is a common first name, and happens to be mine. I use the @lisa username here on GitHub. While being tagged in various repositories is an interesting way for me to discover new projects, it's likely not your intention. Did you mean to tag someone else? Did you mean to use `@lisa` instead, in a [word as word](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction) usage?

# Next Steps

I'm unsubscribing from this issue, pull request or project so if you meant to tag someone else to notify them, I would recommend that. If you meant to use my user ID as a plain string, without having GitHub notify me, you can do so by wrapping with backticks (the \` character), like so: `@lisa`.

**Comment by Munnachienyi** [comment]
hello @baimamboukar have you figured this issue out yet

**Comment by vasconsaurus** [comment]
Hey everyone! 
If this hasn't been done (I couldn't find a PR for this), I think using the same green (`#265F3F`) as in [PR#430](https://github.com/open-life-science/open-life-science.github.io/pull/430) might fix it. 

Since there seems to be no movement on this I'll give this a go, if anyone is working on it, please let me know 🙂

**Comment by vasconsaurus** [comment]
actually, the solution in [PR#430](https://github.com/open-life-science/open-life-science.github.io/pull/430) also fixes this one, since the variable `dark-green` was changed

**Comment by yochannah** [comment]
Closing this issue as out of date. Thanks all! :)
