### ISSUE TITLE
Link to Catalyst site and use catalyst logo

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#771]
Site is here - make sure we link to it in the logical places!

https://catalystproject.cloud/index.html

**Comment by NPDebs** [comment]
Lovely bite-sized gift! 🌷

**Comment by NPDebs** [comment]
✅ It makes sense to link to the new site directly from the navbar.

**Question** - Do we want the logo displayed in the [Catalyst card](https://openlifesci.org/open-incubator.html) in `/open-incubator.html`?

I ask because the other work streams don't have logos. It might be worth considering adding logos for _uniformity_ sake.

💭 Thoughts?

**Comment by bebatut** [comment]
It would be nice to have logo. We could use icons from https://thenounproject.com

**Comment by NPDebs** [comment]
Noted! Thanks for your input...and the resource. 🙏

**Comment by NPDebs** [comment]
Head over to #772, my darlings. 😍 

![open-incubator-icons](https://github.com/open-life-science/open-life-science.github.io/assets/105166953/c962468e-f7ab-4de8-8d6d-4d5b84ea224b)

**Comment by yochannah** [comment]
this black is yummier ;)

**Comment by NPDebs** [comment]
Closed with #772. Thanks!
