### ISSUE TITLE
Fix OLS-8 sub-site dates

### ISSUE THREAD

**Issue by Tajuddeen1** [open-life-science/open-life-science.github.io#858]
On the sub-site https://we-are-ols.org/openseeds/ols-8/ the dates of the cohort call are not correct and when you click on the details of a particular cohort call it takes to OLS-1 instead of OLS-8

**Comment by NPDebs** [comment]
Hi, @Tajuddeen1! Thanks for being observant and opening this issue.

It is a bug that has been fixed by commit [#939a989](https://github.com/open-life-science/open-life-science.github.io/pull/790/commits/939a989d6f3eaa563e86687e4fd99cefc32a96e8) in PR #790. Things will normalise as soon as the PR is merged.

**Comment by NPDebs** [comment]
If it starts to take too long to merge, I might resort to cherry-picking that commit into a separate PR.

**Comment by NPDebs** [comment]
Resolved with #790 merge. Thank you, @Tajuddeen1! 🙏
